<a href="https://colab.research.google.com/github/MOHAMMEDHASSAN1981/AI-MEP-Engineer/blob/main/mynotebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(torch.__version__)
print("Iam very lucky to learn pytorch")

2.0.0+cu118
Iam very lucky to learn pytorch


In [3]:
# Scalar
import torch
scalar = torch.tensor(50)
scalar

tensor(50)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

50

In [8]:
# Vector 
vector =torch.tensor([50,40,40,50])
vector

tensor([50, 40, 40, 50])

In [9]:
# Check the numbers of dimensions 

vector.ndim

1

In [12]:
# Check the shape of the vector
vector.shape

torch.Size([4])

In [21]:
# Matrix
matrix = torch.tensor([[50,30,20,40],[12,15,38,11],[23,55,87,91]])
matrix



tensor([[50, 30, 20, 40],
        [12, 15, 38, 11],
        [23, 55, 87, 91]])

In [22]:
matrix.ndim

2

In [23]:
# Shape of the matrix
matrix.shape

torch.Size([3, 4])

In [38]:
# make a tensor 
TENSOR =torch.tensor([[[[[1,2,3,4],[3,4,5,6],[23,23,43,44],[6,7,8,9],[1,3,5,7]]]]])
TENSOR

tensor([[[[[ 1,  2,  3,  4],
           [ 3,  4,  5,  6],
           [23, 23, 43, 44],
           [ 6,  7,  8,  9],
           [ 1,  3,  5,  7]]]]])

In [39]:
# Check TENSOR dimensions 

TENSOR.ndim

5

In [40]:
# Check the shape of tensos
TENSOR.shape

torch.Size([1, 1, 1, 5, 4])

In [41]:
# Creat Rndom tensor 
random_tensor = torch.rand(size=(4,5))
random_tensor , random_tensor.dtype

(tensor([[0.7173, 0.0147, 0.0184, 0.3660, 0.6547],
         [0.8762, 0.8900, 0.7762, 0.7465, 0.2513],
         [0.8515, 0.3377, 0.4452, 0.9713, 0.9501],
         [0.4534, 0.2087, 0.9530, 0.7725, 0.9667]]),
 torch.float32)