<a href="https://colab.research.google.com/github/MOHAMMEDHASSAN1981/AI-MEP-Engineer/blob/main/pytorch_Fundamentals1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
# Import Recommended libraries 

import torch
import numpy as np
import pandas as np
import matplotlib.pyplot as plt



In [6]:
# Review making random Tensor with 4 rows , 5 column , 3 color (image example)
random_tensor = torch.rand(4,5,3)
random_tensor


tensor([[[0.8967, 0.9193, 0.6735],
         [0.5628, 0.4900, 0.1843],
         [0.4857, 0.6448, 0.4606],
         [0.1336, 0.9335, 0.7383],
         [0.3890, 0.5749, 0.8848]],

        [[0.6588, 0.8290, 0.7429],
         [0.3454, 0.6007, 0.2539],
         [0.9183, 0.5085, 0.0804],
         [0.5580, 0.4716, 0.4832],
         [0.2928, 0.9089, 0.0746]],

        [[0.3030, 0.7870, 0.2627],
         [0.0407, 0.6206, 0.8729],
         [0.7934, 0.7340, 0.1410],
         [0.9703, 0.1457, 0.5938],
         [0.8804, 0.7835, 0.6873]],

        [[0.7563, 0.9048, 0.0855],
         [0.2005, 0.5586, 0.0991],
         [0.3388, 0.5195, 0.5170],
         [0.8159, 0.6859, 0.1488],
         [0.5655, 0.9603, 0.1021]]])

In [7]:
# Zeros & Ones 
# Creat Zeros tensor
zeros = torch.zeros(3,3,6)
zeros


tensor([[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]])

In [10]:
# Creat Ones tensor
ones = torch.ones(2,2,8)
ones

tensor([[[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [11]:
# Creat arange (torch.arange(start = 0 end = 50 step=5))
zeros_arrange = torch.arange(start=0 , end=100 , step= 5)
zeros_arrange

tensor([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
        90, 95])

In [12]:
# creat zeros like input pervious zero_arrange 
zero_like = torch.zeros_like(input=zeros_arrange)
zero_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
# Creat ones like pervious zero_like
ones_like = torch.ones_like(input=zero_like)
ones_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [17]:
# Got informations from tensor torch.shape , torch.dtype , torch.device
some_tensor = torch.rand(3,4,2)
some_tensor.shape

torch.Size([3, 4, 2])

In [18]:
print(f"Shape of tensor : {some_tensor.shape}")


Shape of tensor : torch.Size([3, 4, 2])


In [19]:
print(some_tensor)

tensor([[[0.3888, 0.6581],
         [0.9091, 0.1848],
         [0.6497, 0.2181],
         [0.8298, 0.6725]],

        [[0.7775, 0.2025],
         [0.3918, 0.3450],
         [0.4621, 0.7413],
         [0.4017, 0.3992]],

        [[0.0959, 0.5017],
         [0.3826, 0.9838],
         [0.0039, 0.3942],
         [0.0474, 0.2792]]])
