<a href="https://colab.research.google.com/github/MOHAMMEDHASSAN1981/AI-MEP-Engineer/blob/main/Pytorch_Fundamentals_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**bold text**Tensor datatypes 
torch.cuda tensor used for GPU


In [3]:
# Import essential libraries
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
# Default datatype for tensor is float32 
float32_tensor = torch.tensor([1.2,2.3,3.4,4.5] , 
                              dtype = None, # by default
                              device = None, # by default
                              requires_grad = False) # if True operation recorded on the tensor

float32_tensor.dtype , float32_tensor.device     , float32_tensor.shape                        



(torch.float32, device(type='cpu'), torch.Size([4]))

In [5]:

Float16_tensor = torch.tensor([2.1,3.2,4.3,5.4] , 
                              dtype=torch.float16)
Float16_tensor

tensor([2.0996, 3.1992, 4.3008, 5.3984], dtype=torch.float16)

Manipulating tensors

In [6]:
#addition 
tensor = torch.tensor([1,2,3,4])
tensor + 10

tensor([11, 12, 13, 14])

In [7]:
# Multiplication 
tensor * 10


tensor([10, 20, 30, 40])

In [8]:
# Subtraction 
tensor - 0.5

tensor([0.5000, 1.5000, 2.5000, 3.5000])

In [9]:
# tensor don't change unless reassigned 
tensor



tensor([1, 2, 3, 4])

In [10]:
# Substract and reassigned 
tensor

tensor([1, 2, 3, 4])

In [12]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3, 4])

In [13]:
print(tensor , '*' , tensor)
print("equals :" , tensor * tensor)

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])
equals : tensor([ 1,  4,  9, 16])


In [15]:
# Matrix multiplication 
tensor * tensor

tensor([ 1,  4,  9, 16])

In [16]:
torch.matmul(tensor , tensor)

tensor(30)

In [17]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored