<a href="https://colab.research.google.com/github/MOHAMMEDHASSAN1981/AI-MEP-Engineer/blob/main/pytorch_fundamentals_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**bold text**Tensor datatypes 
torch.cuda tensor used for GPU


In [2]:
# Import essential libraries
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
# Default datatype for tensor is float32 
float32_tensor = torch.tensor([1.2,2.3,3.4,4.5] , 
                              dtype = None, # by default
                              device = None, # by default
                              requires_grad = False) # if True operation recorded on the tensor

float32_tensor.dtype , float32_tensor.device     , float32_tensor.shape                        



(torch.float32, device(type='cpu'), torch.Size([4]))

In [4]:

Float16_tensor = torch.tensor([2.1,3.2,4.3,5.4] , 
                              dtype=torch.float16)
Float16_tensor

tensor([2.0996, 3.1992, 4.3008, 5.3984], dtype=torch.float16)

Manipulating tensors

In [5]:
#addition 
tensor = torch.tensor([1,2,3,4])
tensor + 10

tensor([11, 12, 13, 14])

In [6]:
# Multiplication 
tensor * 10


tensor([10, 20, 30, 40])

In [7]:
# Subtraction 
tensor - 0.5

tensor([0.5000, 1.5000, 2.5000, 3.5000])

In [8]:
# tensor don't change unless reassigned 
tensor



tensor([1, 2, 3, 4])

In [9]:
# Substract and reassigned 
tensor

tensor([1, 2, 3, 4])

In [10]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3, 4])

In [11]:
print(tensor , '*' , tensor)
print("equals :" , tensor * tensor)

tensor([1, 2, 3, 4]) * tensor([1, 2, 3, 4])
equals : tensor([ 1,  4,  9, 16])


In [12]:
# Matrix multiplication 
tensor * tensor

tensor([ 1,  4,  9, 16])

In [13]:
torch.matmul(tensor , tensor)

tensor(30)

In [14]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: ignored

In [15]:
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [16]:
# view tensor_A & tensor_B.T  T: Transpose
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [18]:
# Multiply tensors
torch.mm(tensor_A , tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

MATRIX MULTIBLICATION

In [19]:
# Finding min , max , mean , sum , (aggregation)
# Creat tensor arange
x = torch.arange(0 , 100 , 7)
x

tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [20]:
# Some aggregation
print(f"Minimum : {x.min()}")

Minimum : 0


In [22]:
# Maximum
print(f"Maximum : {x.max()}")
# Mean
print(f"Mean : {x.type(torch.float32).mean()}")
# Median 
print(f"Median : {x.type(torch.float32).median()}")
# Sum
print(f"Sum : {x.sum()}")

Maximum : 98
Mean : 49.0
Median : 49.0
Sum : 735


In [30]:

# Discover torch.max.min.mean.median.sum
print((torch.max(x)) , torch.min(x) , torch.mean(x.type(torch.float32)) ,
torch.median(x.type(torch.float32)) ,
torch.sum(x))

tensor(98) tensor(0) tensor(49.) tensor(49.) tensor(735)


In [33]:
# Postional argument torch.argmax() , torch.argmin()
# Creat a tensor 
tensor = torch.arange(0 ,100 ,10)
print(f"tensor : {tensor}")
# Return index of max and min
print(f"index_max : {tensor.argmax()}")
print(f"index_min : {tensor.argmin()}")


tensor : tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
index_max : 9
index_min : 0


Change tensor data type

In [36]:
# Creat tensor 
tensor = torch.arange(5 ,95 ,10)
print(tensor)
# Change tensor data type 
tensor_float_16 = tensor.type(torch.float16)
print(tensor_float_16.dtype)
# Change tensor data type into integer 8
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8)


tensor([ 5, 15, 25, 35, 45, 55, 65, 75, 85])
torch.float16
tensor([ 5, 15, 25, 35, 45, 55, 65, 75, 85], dtype=torch.int8)


Reshaping, stacking, squeezing and unsqueezing¶